### ISSUE TITLE
Checking about the licensing

### ISSUE THREAD

**Issue by Plecra** [raymanfx/eye-rs#1]
When I recently started working on my own crate, I was surprised by the requirements of the MIT license. I've been wondering whether new crate authors really want to use it for their own projects.

The license requires that any binaries that make use of your crate must  be distributed along with the `LICENSE.txt` file in the repository. I'd expect many users to accidentally break that term, and I personally didn't want to place that burden on them.

Since you can't change the project's license without confirmation from all the contributors, it's something that needs to be addressed early.

So yea, I just wanted to check that you think the MIT license is the most appropriate one for your project 😄 There are a number of other options with simpler, or more friendly terms,

**Comment by raymanfx** [comment]
I'll think about dual-licensing as Apache 2.0.
