### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by SteveGremory** [raymanfx/eye-rs#3]
So i unfortunately am on windows for a day or two and wanted to use this amazing crate, but i can't.
So it's a request from me to you awesome people to add windows support (even tho it's trash)

**Comment by raymanfx** [comment]
Hi, Windows should be supported by the libuvc backend, although I never tested that myself.
Did you try to enable the ˋhal-uvcˋ feature?

**Comment by SteveGremory** [comment]
I'm so sorry, i didn't do that; and i'm sorry for the late reply too. I switched back to linux as i got my own laptop back

**Comment by space-alien** [comment]
Just to let you know I tried enabling ˋhal-uvcˋ on 0.4.1 and ran into a build error:

```
error: failed to run custom build command for `uvc-src v0.2.1`
```

Then various errors along the lines of: `C:\repos\my-repo\target\release\build\uvc-src-3e10995cf4cd1552\out\include\libuvc/libuvc.h(10): fatal error C1083: Cannot open include file: 'sys/time.h': No such file or directory`

A quick Google led me to https://github.com/libuvc/libuvc/issues/105 but that's as far as I've got.

**Comment by raymanfx** [comment]
I cannot really support Windows (apart from trying to keep the libuvc backend alive). Someone else would need to step up to test & fix bugs on Windows.
